[package]
name = "qwaviz"
version = "0.1.0"
edition = "2024"

[dependencies]
num-complex = "0.4.6"
rayon = { version = "1.11.0", optional = true }
three-d = "0.18.2"

[features]
par_braket = ["dep:rayon"]
